"""Central job and installation state vocabulary."""

from enum import StrEnum


class JobStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PREPROCESSING = "PREPROCESSING"
    OCR_RUNNING = "OCR_RUNNING"
    VISION_RUNNING = "VISION_RUNNING"
    MATCHING_HISTORY = "MATCHING_HISTORY"
    FUSING = "FUSING"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    READY = "READY"
    EXPORTING = "EXPORTING"
    EXPORTED = "EXPORTED"
    FAILED = "FAILED"
    FAILED_SCHEMA = "FAILED_SCHEMA"
    DEGRADED = "DEGRADED"


class SetupState(StrEnum):
    SETUP_REQUIRED = "SETUP_REQUIRED"
    READY_FOR_RECOGNITION = "READY_FOR_RECOGNITION"
    DEMO_MODE = "DEMO_MODE"
